<?php

$modelsDir = __DIR__ . '/app/Models';
if (!is_dir($modelsDir)) mkdir($modelsDir, 0777, true);

// Hapus model lama
array_map('unlink', glob("$modelsDir/*.*"));

$migrationsDir = __DIR__ . '/database/migrations';
if (!is_dir($migrationsDir)) mkdir($migrationsDir, 0777, true);

// Hapus migration lama
array_map('unlink', glob("$migrationsDir/*.*"));

// --- Models ---
$models = [
    'Pengguna.php' => "<?php\nnamespace App\Models;\nuse Illuminate\Foundation\Auth\User as Authenticatable;\nuse Illuminate\Notifications\Notifiable;\nclass Pengguna extends Authenticatable\n{\n    use Notifiable;\n    protected \$table = 'pengguna';\n    protected \$primaryKey = 'idpengguna';\n    public \$incrementing = false;\n    protected \$keyType = 'string';\n    protected \$fillable = ['idpengguna', 'email', 'passwordhash', 'role', 'statusakun'];\n    protected \$hidden = ['passwordhash', 'remember_token'];\n    public function getAuthPassword() { return \$this->passwordhash; }\n    public function isAdmin(): bool   { return \$this->role === 'admin'; }\n    public function isDokter(): bool  { return \$this->role === 'dokter'; }\n    public function isPasien(): bool  { return \$this->role === 'pasien'; }\n    public function isPetugas(): bool { return \$this->role === 'petugas'; }\n    public function isKepala(): bool  { return \$this->role === 'kepala'; }\n    public function pasien()    { return \$this->hasOne(Pasien::class, 'idpengguna', 'idpengguna'); }\n    public function dokter()    { return \$this->hasOne(Dokter::class, 'idpengguna', 'idpengguna'); }\n    public function petugas()   { return \$this->hasOne(Petugas::class, 'idpengguna', 'idpengguna'); }\n    public function kepala()    { return \$this->hasOne(KepalaPuskesmas::class, 'idpengguna', 'idpengguna'); }\n}\n",
    'Pasien.php' => "<?php\nnamespace App\Models;\nuse Illuminate\Database\Eloquent\Model;\nclass Pasien extends Model\n{\n    protected \$table = 'pasien';\n    protected \$primaryKey = 'idpasien';\n    public \$incrementing = false;\n    protected \$keyType = 'string';\n    protected \$fillable = ['idpasien', 'idpengguna', 'nik', 'namapasien', 'nomorhp', 'alamat', 'jeniskelamin', 'tanggallahir'];\n    protected \$casts = ['tanggallahir' => 'date'];\n    public function pengguna() { return \$this->belongsTo(Pengguna::class, 'idpengguna', 'idpengguna'); }\n    public function antreans() { return \$this->hasMany(Antrean::class, 'idpasien', 'idpasien'); }\n    public function rekammedis() { return \$this->hasMany(RekamMedis::class, 'idpasien', 'idpasien'); }\n}\n",
    'Dokter.php' => "<?php\nnamespace App\Models;\nuse Illuminate\Database\Eloquent\Model;\nclass Dokter extends Model\n{\n    protected \$table = 'dokter';\n    protected \$primaryKey = 'iddokter';\n    public \$incrementing = false;\n    protected \$keyType = 'string';\n    protected \$fillable = ['iddokter', 'idpengguna', 'namadokter', 'jenisdokter'];\n    public function pengguna()    { return \$this->belongsTo(Pengguna::class, 'idpengguna', 'idpengguna'); }\n    public function jadwals()     { return \$this->hasMany(JadwalLayanan::class, 'iddokter', 'iddokter'); }\n    public function rekammedis()  { return \$this->hasMany(RekamMedis::class, 'iddokter', 'iddokter'); }\n}\n",
    'Petugas.php' => "<?php\nnamespace App\Models;\nuse Illuminate\Database\Eloquent\Model;\nclass Petugas extends Model\n{\n    protected \$table = 'petugas';\n    protected \$primaryKey = 'idpetugas';\n    public \$incrementing = false;\n    protected \$keyType = 'string';\n    protected \$fillable = ['idpetugas', 'idpengguna', 'namapetugas', 'nomorinduk', 'statusaktif', 'shift'];\n    public function pengguna() { return \$this->belongsTo(Pengguna::class, 'idpengguna', 'idpengguna'); }\n    public function antreans() { return \$this->hasMany(Antrean::class, 'idpetugas', 'idpetugas'); }\n}\n",
    'KepalaPuskesmas.php' => "<?php\nnamespace App\Models;\nuse Illuminate\Database\Eloquent\Model;\nclass KepalaPuskesmas extends Model\n{\n    protected \$table = 'kepalapuskesmas';\n    protected \$primaryKey = 'idkepala';\n    public \$incrementing = false;\n    protected \$keyType = 'string';\n    protected \$fillable = ['idkepala', 'idpengguna', 'namakepala', 'nomorinduk', 'periodejabatan'];\n    public function pengguna() { return \$this->belongsTo(Pengguna::class, 'idpengguna', 'idpengguna'); }\n    public function laporans() { return \$this->hasMany(LaporanAntrean::class, 'idkepala', 'idkepala'); }\n}\n",
    'Poli.php' => "<?php\nnamespace App\Models;\nuse Illuminate\Database\Eloquent\Model;\nclass Poli extends Model\n{\n    protected \$table = 'poli';\n    protected \$primaryKey = 'idpoli';\n    public \$incrementing = false;\n    protected \$keyType = 'string';\n    protected \$fillable = ['idpoli', 'namapoli', 'kuotaharian', 'statusbuka', 'jamoperasional'];\n    public function jadwals()  { return \$this->hasMany(JadwalLayanan::class, 'idpoli', 'idpoli'); }\n    public function laporans() { return \$this->hasMany(LaporanAntrean::class, 'idpoli', 'idpoli'); }\n    public function kuotaTersisaHariIni(): int\n    {\n        \$terisi = Antrean::whereHas('jadwal', function (\$q) {\n            \$q->where('idpoli', \$this->idpoli);\n        })->whereHas('jadwal', function (\$q) {\n            \$q->where('tanggal', today());\n        })->whereIn('status', ['menunggu', 'dipanggil'])->count();\n        return max(0, \$this->kuotaharian - \$terisi);\n    }\n}\n",
    'JadwalLayanan.php' => "<?php\nnamespace App\Models;\nuse Illuminate\Database\Eloquent\Model;\nclass JadwalLayanan extends Model\n{\n    protected \$table = 'jadwallayanan';\n    protected \$primaryKey = 'idjadwal';\n    public \$incrementing = false;\n    protected \$keyType = 'string';\n    protected \$fillable = ['idjadwal', 'idpoli', 'iddokter', 'tanggal', 'kuotamaksimal', 'kuotaterisi', 'status'];\n    protected \$casts = ['tanggal' => 'date'];\n    public function poli()     { return \$this->belongsTo(Poli::class, 'idpoli', 'idpoli'); }\n    public function dokter()   { return \$this->belongsTo(Dokter::class, 'iddokter', 'iddokter'); }\n    public function antreans() { return \$this->hasMany(Antrean::class, 'idjadwal', 'idjadwal'); }\n    public function sisaKuota(): int { return max(0, \$this->kuotamaksimal - \$this->kuotaterisi); }\n    public function isFull(): bool   { return \$this->kuotaterisi >= \$this->kuotamaksimal; }\n}\n",
    'Antrean.php' => "<?php\nnamespace App\Models;\nuse Illuminate\Database\Eloquent\Model;\nclass Antrean extends Model\n{\n    protected \$table = 'antrean';\n    protected \$primaryKey = 'idantrean';\n    public \$incrementing = false;\n    protected \$keyType = 'string';\n    protected \$fillable = [\n        'idantrean', 'idpasien', 'idjadwal', 'idpetugas',\n        'nomorantrean', 'status', 'alasanbatal',\n        'waktudaftar', 'waktupanggil', 'waktuselesai',\n        'estimasitunggu', 'jenispasien',\n    ];\n    protected \$casts = [\n        'waktudaftar'   => 'datetime',\n        'waktupanggil'  => 'datetime',\n        'waktuselesai'  => 'datetime',\n    ];\n    public function pasien()  { return \$this->belongsTo(Pasien::class, 'idpasien', 'idpasien'); }\n    public function jadwal()  { return \$this->belongsTo(JadwalLayanan::class, 'idjadwal', 'idjadwal'); }\n    public function petugas() { return \$this->belongsTo(Petugas::class, 'idpetugas', 'idpetugas'); }\n    public function notifikasis() { return \$this->hasMany(Notifikasi::class, 'idantrean', 'idantrean'); }\n    public function rekammedis()  { return \$this->hasOne(RekamMedis::class, 'idantrean', 'idantrean'); }\n    public function statusBadgeClass(): string\n    {\n        return match(\$this->status) {\n            'menunggu'  => 'bg-tertiary-fixed text-on-tertiary-fixed-variant',\n            'dipanggil' => 'bg-primary text-on-primary animate-pulse',\n            'selesai'   => 'bg-secondary-container text-on-secondary-container',\n            'batal'     => 'bg-error-container text-on-error-container',\n            default     => 'bg-outline-variant text-on-surface',\n        };\n    }\n    public static function generateNomor(string \$idpoli, string \$tanggal): string\n    {\n        \$poli = Poli::find(\$idpoli);\n        \$kode = strtoupper(substr(\$poli->namapoli, -1));\n        \$count = self::whereHas('jadwal', function (\$q) use (\$idpoli, \$tanggal) {\n            \$q->where('idpoli', \$idpoli)->where('tanggal', \$tanggal);\n        })->count();\n        return \$kode . '-' . str_pad(\$count + 1, 3, '0', STR_PAD_LEFT);\n    }\n}\n",
    'RekamMedis.php' => "<?php\nnamespace App\Models;\nuse Illuminate\Database\Eloquent\Model;\nclass RekamMedis extends Model\n{\n    protected \$table = 'rekammedis';\n    protected \$primaryKey = 'idrekammedis';\n    public \$incrementing = false;\n    protected \$keyType = 'string';\n    protected \$fillable = ['idrekammedis', 'idpasien', 'iddokter', 'idantrean', 'keluhan', 'diagnosis', 'resep', 'tanggalperiksa'];\n    protected \$casts = ['tanggalperiksa' => 'datetime'];\n    public function pasien()  { return \$this->belongsTo(Pasien::class, 'idpasien', 'idpasien'); }\n    public function dokter()  { return \$this->belongsTo(Dokter::class, 'iddokter', 'iddokter'); }\n    public function antrean() { return \$this->belongsTo(Antrean::class, 'idantrean', 'idantrean'); }\n}\n",
    'Notifikasi.php' => "<?php\nnamespace App\Models;\nuse Illuminate\Database\Eloquent\Model;\nclass Notifikasi extends Model\n{\n    protected \$table = 'notifikasi';\n    protected \$primaryKey = 'idnotifikasi';\n    public \$incrementing = false;\n    protected \$keyType = 'string';\n    protected \$fillable = ['idnotifikasi', 'idantrean', 'jenisnotifikasi', 'pesan', 'statuskirim', 'waktukirim', 'nomortujuan'];\n    protected \$casts = ['waktukirim' => 'datetime'];\n    public function antrean() { return \$this->belongsTo(Antrean::class, 'idantrean', 'idantrean'); }\n}\n",
    'LaporanAntrean.php' => "<?php\nnamespace App\Models;\nuse Illuminate\Database\Eloquent\Model;\nclass LaporanAntrean extends Model\n{\n    protected \$table = 'laporanantrean';\n    protected \$primaryKey = 'idlaporan';\n    public \$incrementing = false;\n    protected \$keyType = 'string';\n    protected \$fillable = ['idlaporan', 'idkepala', 'idpoli', 'tgllaporan', 'totalpasien', 'totalselesai', 'totalbatal', 'ratawaktutunggu', 'totaltidakhadir'];\n    protected \$casts = ['tgllaporan' => 'date'];\n    public function kepala() { return \$this->belongsTo(KepalaPuskesmas::class, 'idkepala', 'idkepala'); }\n    public function poli()   { return \$this->belongsTo(Poli::class, 'idpoli', 'idpoli'); }\n}\n"
];

foreach ($models as $filename => $content) {
    file_put_contents($modelsDir . '/' . $filename, $content);
}

// --- Migrations ---
$migrations = [
    '2026_06_03_000001_create_pengguna_table.php' => "<?php\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\nreturn new class extends Migration {\n    public function up(): void {\n        Schema::create('pengguna', function (Blueprint \$table) {\n            \$table->string('idpengguna', 12)->primary();\n            \$table->string('email', 100)->unique();\n            \$table->string('passwordhash', 255);\n            \$table->enum('role', ['admin', 'pasien', 'dokter', 'petugas', 'kepala']);\n            \$table->string('statusakun', 10)->default('aktif');\n            \$table->rememberToken();\n            \$table->timestamps();\n        });\n    }\n    public function down(): void { Schema::dropIfExists('pengguna'); }\n};",
    '2026_06_03_000002_create_poli_table.php' => "<?php\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\nreturn new class extends Migration {\n    public function up(): void {\n        Schema::create('poli', function (Blueprint \$table) {\n            \$table->string('idpoli', 10)->primary();\n            \$table->string('namapoli', 100);\n            \$table->integer('kuotaharian')->default(30);\n            \$table->enum('statusbuka', ['buka', 'tutup'])->default('buka');\n            \$table->string('jamoperasional', 50)->default('07:30-14:00');\n            \$table->timestamps();\n        });\n    }\n    public function down(): void { Schema::dropIfExists('poli'); }\n};",
    '2026_06_03_000003_create_pasien_table.php' => "<?php\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\nreturn new class extends Migration {\n    public function up(): void {\n        Schema::create('pasien', function (Blueprint \$table) {\n            \$table->string('idpasien', 12)->primary();\n            \$table->string('idpengguna', 12);\n            \$table->char('nik', 16)->unique();\n            \$table->string('namapasien', 100);\n            \$table->string('nomorhp', 15)->nullable();\n            \$table->string('alamat', 255)->nullable();\n            \$table->enum('jeniskelamin', ['L', 'P'])->nullable();\n            \$table->date('tanggallahir')->nullable();\n            \$table->timestamps();\n            \$table->foreign('idpengguna')->references('idpengguna')->on('pengguna')->onDelete('cascade');\n        });\n    }\n    public function down(): void { Schema::dropIfExists('pasien'); }\n};",
    '2026_06_03_000004_create_dokter_table.php' => "<?php\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\nreturn new class extends Migration {\n    public function up(): void {\n        Schema::create('dokter', function (Blueprint \$table) {\n            \$table->string('iddokter', 12)->primary();\n            \$table->string('idpengguna', 12);\n            \$table->string('namadokter', 100);\n            \$table->string('jenisdokter', 100)->nullable();\n            \$table->timestamps();\n            \$table->foreign('idpengguna')->references('idpengguna')->on('pengguna')->onDelete('cascade');\n        });\n    }\n    public function down(): void { Schema::dropIfExists('dokter'); }\n};",
    '2026_06_03_000005_create_petugas_table.php' => "<?php\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\nreturn new class extends Migration {\n    public function up(): void {\n        Schema::create('petugas', function (Blueprint \$table) {\n            \$table->string('idpetugas', 12)->primary();\n            \$table->string('idpengguna', 12);\n            \$table->string('namapetugas', 100);\n            \$table->string('nomorinduk', 20)->nullable();\n            \$table->enum('statusaktif', ['aktif', 'nonaktif'])->default('aktif');\n            \$table->enum('shift', ['pagi', 'siang', 'malam'])->default('pagi');\n            \$table->timestamps();\n            \$table->foreign('idpengguna')->references('idpengguna')->on('pengguna')->onDelete('cascade');\n        });\n    }\n    public function down(): void { Schema::dropIfExists('petugas'); }\n};",
    '2026_06_03_000006_create_kepalapuskesmas_table.php' => "<?php\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\nreturn new class extends Migration {\n    public function up(): void {\n        Schema::create('kepalapuskesmas', function (Blueprint \$table) {\n            \$table->string('idkepala', 12)->primary();\n            \$table->string('idpengguna', 12);\n            \$table->string('namakepala', 100);\n            \$table->string('nomorinduk', 20)->nullable();\n            \$table->string('periodejabatan', 50)->nullable();\n            \$table->timestamps();\n            \$table->foreign('idpengguna')->references('idpengguna')->on('pengguna')->onDelete('cascade');\n        });\n    }\n    public function down(): void { Schema::dropIfExists('kepalapuskesmas'); }\n};",
    '2026_06_03_000007_create_jadwallayanan_table.php' => "<?php\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\nreturn new class extends Migration {\n    public function up(): void {\n        Schema::create('jadwallayanan', function (Blueprint \$table) {\n            \$table->string('idjadwal', 10)->primary();\n            \$table->string('idpoli', 10);\n            \$table->string('iddokter', 12);\n            \$table->date('tanggal');\n            \$table->integer('kuotamaksimal')->default(20);\n            \$table->integer('kuotaterisi')->default(0);\n            \$table->enum('status', ['aktif', 'nonaktif'])->default('aktif');\n            \$table->timestamps();\n            \$table->foreign('idpoli')->references('idpoli')->on('poli')->onDelete('cascade');\n            \$table->foreign('iddokter')->references('iddokter')->on('dokter')->onDelete('cascade');\n        });\n    }\n    public function down(): void { Schema::dropIfExists('jadwallayanan'); }\n};",
    '2026_06_03_000008_create_antrean_table.php' => "<?php\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\nreturn new class extends Migration {\n    public function up(): void {\n        Schema::create('antrean', function (Blueprint \$table) {\n            \$table->string('idantrean', 10)->primary();\n            \$table->string('idpasien', 12);\n            \$table->string('idjadwal', 10);\n            \$table->string('idpetugas', 12)->nullable();\n            \$table->string('nomorantrean', 10);\n            \$table->enum('status', ['menunggu', 'dipanggil', 'selesai', 'batal'])->default('menunggu');\n            \$table->string('alasanbatal', 255)->nullable();\n            \$table->dateTime('waktudaftar')->nullable();\n            \$table->dateTime('waktupanggil')->nullable();\n            \$table->dateTime('waktuselesai')->nullable();\n            \$table->integer('estimasitunggu')->nullable();\n            \$table->enum('jenispasien', ['BPJS', 'UMUM'])->default('UMUM');\n            \$table->timestamps();\n            \$table->foreign('idpasien')->references('idpasien')->on('pasien')->onDelete('cascade');\n            \$table->foreign('idjadwal')->references('idjadwal')->on('jadwallayanan')->onDelete('cascade');\n            \$table->foreign('idpetugas')->references('idpetugas')->on('petugas')->onDelete('set null');\n        });\n    }\n    public function down(): void { Schema::dropIfExists('antrean'); }\n};",
    '2026_06_03_000009_create_rekammedis_table.php' => "<?php\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\nreturn new class extends Migration {\n    public function up(): void {\n        Schema::create('rekammedis', function (Blueprint \$table) {\n            \$table->string('idrekammedis', 12)->primary();\n            \$table->string('idpasien', 12);\n            \$table->string('iddokter', 12);\n            \$table->string('idantrean', 10);\n            \$table->string('keluhan', 255)->nullable();\n            \$table->string('diagnosis', 255)->nullable();\n            \$table->text('resep')->nullable();\n            \$table->dateTime('tanggalperiksa')->nullable();\n            \$table->timestamps();\n            \$table->foreign('idpasien')->references('idpasien')->on('pasien')->onDelete('cascade');\n            \$table->foreign('iddokter')->references('iddokter')->on('dokter')->onDelete('cascade');\n            \$table->foreign('idantrean')->references('idantrean')->on('antrean')->onDelete('cascade');\n        });\n    }\n    public function down(): void { Schema::dropIfExists('rekammedis'); }\n};",
    '2026_06_03_000010_create_notifikasi_table.php' => "<?php\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\nreturn new class extends Migration {\n    public function up(): void {\n        Schema::create('notifikasi', function (Blueprint \$table) {\n            \$table->string('idnotifikasi', 10)->primary();\n            \$table->string('idantrean', 10);\n            \$table->enum('jenisnotifikasi', ['pendaftaran', 'panggilan', 'pembatalan', 'selesai'])->default('pendaftaran');\n            \$table->text('pesan');\n            \$table->enum('statuskirim', ['pending', 'terkirim', 'gagal'])->default('pending');\n            \$table->dateTime('waktukirim')->nullable();\n            \$table->string('nomortujuan', 15)->nullable();\n            \$table->timestamps();\n            \$table->foreign('idantrean')->references('idantrean')->on('antrean')->onDelete('cascade');\n        });\n    }\n    public function down(): void { Schema::dropIfExists('notifikasi'); }\n};",
    '2026_06_03_000011_create_laporanantrean_table.php' => "<?php\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\nreturn new class extends Migration {\n    public function up(): void {\n        Schema::create('laporanantrean', function (Blueprint \$table) {\n            \$table->string('idlaporan', 10)->primary();\n            \$table->string('idkepala', 12);\n            \$table->string('idpoli', 10);\n            \$table->date('tgllaporan');\n            \$table->integer('totalpasien')->default(0);\n            \$table->integer('totalselesai')->default(0);\n            \$table->integer('totalbatal')->default(0);\n            \$table->decimal('ratawaktutunggu', 10, 2)->default(0);\n            \$table->integer('totaltidakhadir')->default(0);\n            \$table->timestamps();\n            \$table->foreign('idkepala')->references('idkepala')->on('kepalapuskesmas')->onDelete('cascade');\n            \$table->foreign('idpoli')->references('idpoli')->on('poli')->onDelete('cascade');\n        });\n    }\n    public function down(): void { Schema::dropIfExists('laporanantrean'); }\n};",
    '2026_06_03_000012_create_cache_table.php' => "<?php\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\nreturn new class extends Migration {\n    public function up(): void {\n        Schema::create('cache', function (Blueprint \$table) {\n            \$table->string('key')->primary();\n            \$table->mediumText('value');\n            \$table->bigInteger('expiration')->index();\n        });\n        Schema::create('cache_locks', function (Blueprint \$table) {\n            \$table->string('key')->primary();\n            \$table->string('owner');\n            \$table->bigInteger('expiration')->index();\n        });\n    }\n    public function down(): void {\n        Schema::dropIfExists('cache');\n        Schema::dropIfExists('cache_locks');\n    }\n};",
    '2026_06_03_000013_create_jobs_table.php' => "<?php\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\nreturn new class extends Migration {\n    public function up(): void {\n        Schema::create('jobs', function (Blueprint \$table) {\n            \$table->id();\n            \$table->string('queue')->index();\n            \$table->longText('payload');\n            \$table->unsignedSmallInteger('attempts');\n            \$table->unsignedInteger('reserved_at')->nullable();\n            \$table->unsignedInteger('available_at');\n            \$table->unsignedInteger('created_at');\n        });\n        Schema::create('job_batches', function (Blueprint \$table) {\n            \$table->string('id')->primary();\n            \$table->string('name');\n            \$table->integer('total_jobs');\n            \$table->integer('pending_jobs');\n            \$table->integer('failed_jobs');\n            \$table->longText('failed_job_ids');\n            \$table->mediumText('options')->nullable();\n            \$table->integer('cancelled_at')->nullable();\n            \$table->integer('created_at');\n            \$table->integer('finished_at')->nullable();\n        });\n        Schema::create('failed_jobs', function (Blueprint \$table) {\n            \$table->id();\n            \$table->string('uuid')->unique();\n            \$table->string('connection');\n            \$table->string('queue');\n            \$table->longText('payload');\n            \$table->longText('exception');\n            \$table->timestamp('failed_at')->useCurrent();\n            \$table->index(['connection', 'queue', 'failed_at']);\n        });\n    }\n    public function down(): void {\n        Schema::dropIfExists('jobs');\n        Schema::dropIfExists('job_batches');\n        Schema::dropIfExists('failed_jobs');\n    }\n};",
    '2026_06_03_000014_create_sessions_table.php' => "<?php\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\nreturn new class extends Migration {\n    public function up(): void {\n        Schema::create('sessions', function (Blueprint \$table) {\n            \$table->string('id')->primary();\n            \$table->string('user_id', 12)->nullable();\n            \$table->string('ip_address', 45)->nullable();\n            \$table->text('user_agent')->nullable();\n            \$table->text('payload');\n            \$table->integer('last_activity');\n        });\n    }\n    public function down(): void { Schema::dropIfExists('sessions'); }\n};"
];

foreach ($migrations as $filename => $content) {
    file_put_contents($migrationsDir . '/' . $filename, $content);
}

echo "Files created successfully.";
